// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgdNPxrkfEEZSVFeFN-7wmxby0j_3vGVQ',
    appId: '1:822587445550:web:b0cf26d92cbe91bd00eabf',
    messagingSenderId: '822587445550',
    projectId: 'ecommerceapp-b13d3',
    authDomain: 'ecommerceapp-b13d3.firebaseapp.com',
    storageBucket: 'ecommerceapp-b13d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpz47naq7pRJ0TmP4wzfFJ1MJUkQaF0Po',
    appId: '1:822587445550:android:9370f1b12d51e7a800eabf',
    messagingSenderId: '822587445550',
    projectId: 'ecommerceapp-b13d3',
    storageBucket: 'ecommerceapp-b13d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqL8bpZKvKCkGnOz98YcdoY3Z8iOObZA',
    appId: '1:822587445550:ios:1bd5975cf0398fa500eabf',
    messagingSenderId: '822587445550',
    projectId: 'ecommerceapp-b13d3',
    storageBucket: 'ecommerceapp-b13d3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqL8bpZKvKCkGnOz98YcdoY3Z8iOObZA',
    appId: '1:822587445550:ios:1bd5975cf0398fa500eabf',
    messagingSenderId: '822587445550',
    projectId: 'ecommerceapp-b13d3',
    storageBucket: 'ecommerceapp-b13d3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgdNPxrkfEEZSVFeFN-7wmxby0j_3vGVQ',
    appId: '1:822587445550:web:2ef52fd8110f325e00eabf',
    messagingSenderId: '822587445550',
    projectId: 'ecommerceapp-b13d3',
    authDomain: 'ecommerceapp-b13d3.firebaseapp.com',
    storageBucket: 'ecommerceapp-b13d3.firebasestorage.app',
  );
}
